### ISSUE TITLE
@Factory annotation of Hamcrest is missing

### ISSUE THREAD

**Issue by jethroborsje** [hamcrest/hamcrest-junit#15]
This project is missing the org.hamcrest.Factory annotation. Is this going to be added?

**Comment by sf105** [comment]
If it belongs anywhere, it belongs in the JavaHamcrest project. Actually, we're in the process of removing it.

**Comment by ericslandry** [comment]
I'm porting code from 1.3 to 2.0 and second @jethroborsje 's question. I'm not sure where to go from here.

@sf105 : I know it's been a while, but would you be so kind as to elaborate on your previous comment? Thanks!!!

**Comment by UrsMetz** [comment]
@ericslandry I think @sf105 refers to hamcrest/JavaHamcrest#84 (cf. also hamcrest/JavaHamcrest@425f095).
