### ISSUE TITLE
Please use ErrorCollector from JUnit 4.12

### ISSUE THREAD

**Issue by marcphilipp** [hamcrest/hamcrest-junit#5]
In JUnit 4.12 junit-team/junit@60aaf96322abf2071e4f93b2748723a56c5ee668 has made `checkSucceeds` generic.

Please use this version for hamcrest-junit:
https://github.com/junit-team/junit/blob/r4.12/src/main/java/org/junit/rules/ErrorCollector.java

**Comment by josephw** [comment]
This change is also included in #3, which brings over all the changes from JUnit 4.12.

@marcphilipp, is there a reasonable list of fixes to cherry-pick across, or is wholesale re-copying of the classes going to make transition easier?

**Comment by marcphilipp** [comment]
@josephw I'm afraid there's no such list. I would go for copying the classes from the r4.12 tag over and trying to split the changes into meaningful commits. Do you have time to do it or should I take a stab?

**Comment by josephw** [comment]
I have time to do that; I'd like to make sure it's an acceptable form.

Would all the changes from the 4.12 tag, with a single commit for reformatting and a separate commit for each other change, with brief descriptions, all in a single PR be acceptable?

**Comment by marcphilipp** [comment]
@npryce What do you think?

**Comment by npryce** [comment]
Merged PR#8, so I believe this issue can be closed.
