### ISSUE TITLE
hamcrest-junit 2.0.0.0 does not work with JDK 6

### ISSUE THREAD

**Issue by marcphilipp** [hamcrest/hamcrest-junit#6]
The same issue as hamcrest/JavaHamcrest#105 is also present in hamcrest-junit 2.0.0.0.

**Comment by npryce** [comment]
See hamcrest/JavaHamcrest#105: if Hamcrest 2.x.y.z depends on Java 7+, then hamcrest-junit can also. If JUnit is decoupled from Hamcrest via Hamcrest-JUnit then this should not cause problems for people who want to use JUnit on Java 6. They can continue to use MatcherAssert in Hamcrest 1.3.

**Comment by npryce** [comment]
I've released Hamcrest-JUnit 1.0.0.1, which is compiled with JDK 1.6.
