### ISSUE TITLE
Switch to Gradle 2.4 

### ISSUE THREAD

**Issue by vogella** [hamcrest/hamcrest-junit#9]
The Eclipse Gradle tooling does not support Gradle 2.0 which is currently used in gradlew for Hamcrest. See https://bugs.eclipse.org/bugs/show_bug.cgi?id=468952

Would it possible for you to switch to Gradle 2.4?

**Comment by npryce** [comment]
Merged PR

**Comment by vogella** [comment]
Cool, thanks @npryce
